/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package it.intecs.pisa.soap.toolbox;

/**
 *
 * @author Massimiliano
 */
public interface IToolboxEngineConstants {
    String CONFIGURATION_FTP_SERVER_MANAGER = "CONFIGURATION_FTP_SERVER_MANAGER";
    String CONFIGURATION_MARKERS = "CONFIGURATION_MARKERS";
    String CONFIGURATION_RESULT_SCRIPT = "CONFIGURATION_RESULT_SCRIPT";
    String CONFIGURATION_RESULT_SCRIPT_FILE = "CONFIGURATION_RESULT_SCRIPT_FILE";
    String CONFIGURATION_SERVICE_LOGGER = "CONFIGURATION_SERVICE_LOGGER";
    String CONFIGURATION_SERVICE_RESOURCE_DIR = "CONFIGURATION_SERVICE_RESOURCE_DIR";
    String CONFIGURATION_TEMP_DIR = "CONFIGURATION_TEMP_DIR";
    String CONFIGURATION_TEXT_NAVIGATOR = "CONFIGURATION_TEXT_NAVIGATOR";
    String CONFIGURATION_TIMER_MANAGER = "CONFIGURATION_TIMER_MANAGER";

}
